---
- name: Upgrade all packages
  yum: name=* state=latest

- name: Install essential packages
  yum: name={{ item }} state=latest
  with_items:
    - bzip2-devel
    - curl-devel
    - gcc
    - gcc-c++
    - git
    - ImageMagick-devel
    - make
    - nodejs
    - openssl-devel
    - patch
    - sudo
    - tar
    - v8-devel
    - zlib-devel
    - ImageMagick
    - ImageMagick-devel

- name: Ensure app folder exists
  file:
    path: "{{ app_placeholder_directory }}"
    state: directory

- name: Symlink app folder to shared folder
  file:
    src: /vagrant
    dest: "{{ apache_document_root }}"
    state: link
  when: is_dev is defined and is_dev
