---
# common
base_url: woo.ec.local
app_name: woo
app_placeholder_directory: /home/test/ec
apache_document_root: "{{ app_placeholder_directory }}/{{ app_name}}"
is_dev: True

# deploy_user
deploy_user_name: vagrant

# apache
apache_enablerepo: remi
apache_remove_default_vhost: True
apache_vhosts_filename: "{{ base_url }}.conf"
apache_vhosts:
  - servername: "{{ base_url }}"
    documentroot: "{{ apache_document_root }}"
    extra_parameters: |
      Redirect permanent / https://{{ base_url }}/
apache_vhosts_ssl:
  - servername: "{{ base_url }}"
    documentroot: "{{ apache_document_root }}"
    certificate_file: "/etc/ssl/{{ base_url }}/{{ base_url }}.pem"
    certificate_key_file: "/etc/ssl/{{ base_url }}/{{ base_url }}.key"
    certificate_chain_file: "/etc/ssl/{{ base_url }}/{{ base_url }}.combined.pem"
    extra_parameters: |
      CustomLog '|/usr/sbin/rotatelogs /var/log/httpd/ssl_{{ base_url }}_%Y%m%d-access_log 86400 540' combined
      ErrorLog '|/usr/sbin/rotatelogs /var/log/httpd/ssl_{{ base_url }}_%Y%m%d-error_log 86400 540'

# ssl-certs
ssl_certs_path_owner: "root"
ssl_certs_path_group: "root"
ssl_certs_country: "VN"
ssl_certs_locality: "Ho Chi Minh"
ssl_certs_organization: "ORO Vietnam"
ssl_certs_state: "Ho Chi Minh"
ssl_certs_common_name: "{{ base_url }}"

# mysql
mysql_enablerepo: remi
mysql_databases:
  - name: ec_woo_prod
    collation: utf8_general_ci
    encoding: utf8
mysql_users:
  - name: "ec"
    host: "%"
    password: "root"
    priv: "ec_woo_prod.*:ALL"

# php
php_source_configure_command: >
  ./configure
  --prefix={{ php_source_install_path }}
  --with-config-file-path={{ php_conf_paths | first }}
  --enable-mbstring
  --enable-zip
  --enable-bcmath
  --enable-pcntl
  --enable-ftp
  --enable-exif
  --enable-calendar
  --enable-opcache
  --enable-pdo
  --enable-suhosin
  --enable-sysvmsg
  --enable-sysvsem
  --enable-sysvshm
  --enable-wddx
  --with-curl
  --with-mcrypt
  --with-iconv
  --with-gmp
  --with-pspell
  --with-gd
  --with-jpeg-dir=/usr
  --with-png-dir=/usr
  --with-zlib-dir=/usr
  --with-xpm-dir=/usr
  --with-freetype-dir=/usr
  --enable-gd-native-ttf
  --enable-gd-jis-conv
  --with-openssl
  --with-pdo-mysql=/usr
  --with-gettext=/usr
  --with-zlib=/usr
  --with-bz2=/usr
  --with-recode=/usr
  --with-mysqli=/usr/bin/mysql_config

# php-versions
php_version: '7.2'

# php-xdebug
php_xdebug_version: 2.6.0
php_xdebug_idekey: OROVietnam
php_xdebug_remote_enable: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_host: woo.ec.local

# composer
composer_global_packages:
   - { name: hirak/prestissimo }
   - { name: wp-cli/wp-cli }

# ruby
ruby_install_from_source: True
