---
- name: Install logrotate
  package:
    name: logrotate
    state: present

- name: Ensure libselinux-python installed
  yum:
    name: libselinux-python
    state: latest

- name: Setup logrotate.conf
  template:
    src: logrotate.conf.j2
    dest: /etc/logrotate.conf

- name: Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}/{{ item.name }}"
  with_items: "{{ logrotate_scripts }}"
  when: logrotate_scripts is defined
